import Head from 'next/head'
import { useCount, useDispatchCount } from '../src/context/Counter'
import styles from '../styles/Home.module.css'

import React from 'react';
import Link from 'next/link'
import ShowCounter from '../src/components/ShowCounter';
export default function Home() {

  const count = useCount()
  const dispatch = useDispatchCount()

  const handleIncrease = (event: React.MouseEvent<HTMLElement>) =>
    dispatch({
      type: 'INCREASE',
    })
  const handleDecrease = (event: React.MouseEvent<HTMLElement>) =>
    dispatch({
      type: 'DECREASE',
    })

  const myNumber = (event: React.MouseEvent<HTMLElement>) =>
    dispatch({
      type: 'INCREASE_BY',
      payload: 20
    })

  return (
    <div className={styles.container}>
      <Head>
        <title>Felipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/">
          <a>Index</a>
        </Link>
        <p>Counter: {count}</p>
        <button onClick={handleIncrease}>Increase</button>
        <button onClick={handleDecrease}>Decrease</button>
        <button onClick={myNumber}>myNumber</button>
        <br />
        <div>
          <div>showcounter component below</div>
          <div>
            <ShowCounter />
          </div>
        </div>
      </main>

    </div>
  )
}
