import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Autocomplete from '@material-ui/lab/Autocomplete';
import { TextField } from '@material-ui/core';
import React from 'react';

export default function Home() {

  const top100Films = [
    { title: 'Vietna Travel Group', year: 1994 },
    { title: 'WorldLink', year: 1972 },
    { title: 'NewLife BacNinh', year: 1974 },
  ];

  const [selected, setSelected] = React.useState<{ title: string, year: number } | null>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Autocomplete
          getOptionSelected={(option, value) => option.title === value.title}
          onChange={(e, v) => setSelected(v)}
          id="combo-box-demo"
          options={top100Films}
          getOptionLabel={(option) => option.title}
          style={{ width: 500 }}
          renderInput={(params) => <TextField {...params} label="Find the company" variant="outlined" />}
        />


      </main>

    </div>
  )
}
